### ISSUE TITLE
How do I get the serial number in the List style, do not use ol 

### ISSUE THREAD

**Issue by cooliean** [mwilliamson/mammoth.js#104]
I want get the  A、B、C、D....
thank you

**Comment by mwilliamson** [comment]
Mammoth intentionally only extracts the semantics of the document, which is why it produces an `ol` element. If you want to display A, B, C, etc as the labels for each item, then you have two choices:

* use CSS to style the `ol`, specifically `list-style-type: upper-alpha`
* write some post-processing that finds `ol` elements and adds in the desired numbering
