### ISSUE TITLE
Is there a way to ignore images in the output file?

### ISSUE THREAD

**Issue by VulcanRav** [mwilliamson/mammoth.js#140]
I have an original file with lots of images I'm not really interested in having in the final html.

I thought about using the rawtext option but I need to keep the formatting.

**Comment by mwilliamson** [comment]
At the moment, you have two options:

* use a document transform to strip out the image elements after the document has been parsed, but before the HTML is generated

* post-process the HTML to strip out the images

If it works for you, I'd strongly suggest post-processing the HTML since it's going to be more reliable between different versions of Mammoth.
