### ISSUE TITLE
w:softHyphen support

### ISSUE THREAD

**Issue by maddesigns** [mwilliamson/mammoth.js#161]
does mammoth support `<w:softHyphen>`?

**Comment by mwilliamson** [comment]
Not at the moment, no.

**Comment by sfinktah** [comment]
Just as a technical note (since I noticed this warning myself, although I don't care), soft hyphens can be rendered in html as:

    &shy;

Yeah, I know it only takes 60 seconds to google that up for yourself, but if you're like me, avoiding the effort can mean the difference between fixing and not fixing a small thing.  Not that it needs to be "fixed" of course.

**Comment by mwilliamson** [comment]
Soft hyphens should now be supported in the latest version.
