### ISSUE TITLE
Problem_6: New heading is clubbed to a preceding list as new list item 

### ISSUE THREAD

**Issue by Dinesh-Mali** [mwilliamson/mammoth.js#204]
Hello,
1) If there is a list followed by some heading, then that heading is clubbed inside the list as new list item,
2) Other points also noted from this issue that, alphabetical list type are converted to numerical types, Heading 4 was on new page that was again converted as heading 1.
Please guide to resolve this issue.
PFA,
![Issue_6](https://user-images.githubusercontent.com/29540745/62452462-dbf44000-b78d-11e9-81a2-baf3172a92f3.PNG)
![Issue_6_html](https://user-images.githubusercontent.com/29540745/62452463-dbf44000-b78d-11e9-96c4-abf7fd005666.PNG)

**Comment by mwilliamson** [comment]
Example document from #199:

> Problem_6:
> [problem_6.docx](https://github.com/mwilliamson/mammoth.js/files/3470619/problem_6.docx)
> [problem_6.txt](https://github.com/mwilliamson/mammoth.js/files/3470620/problem_6.txt)

The problem is that Mammoth ignores the direct formatting, and just uses the style information from the document. Since both lists are top-level lists using the default style, Mammoth has no way of distinguishing the two. I'd suggest using a separate style for the headings, and if not using one of the built-in heading styles, adding a style mapping for that heading style.
