### ISSUE TITLE
How to get rid of styling elements (id and class)

### ISSUE THREAD

**Issue by hiddenchamp** [mwilliamson/mammoth.js#325]
Whenever I import a docx file, some weird styling elements get added as well. Then I have to remove all of them manually.

Stuff like:
`<h2><a id="post-630-_xshcf5d1hnq6">`
or
`<img class="wp-image-632"`

Is there  way to stop importing these IDs and Classes?
I just want a simple h2 and img tag.

**Comment by mwilliamson** [comment]
The anchor tags are generated from the bookmarks in the source document. If you remove the bookmarks, then the corresponding anchor tags should disappear.

Mammoth.js doesn't add any classes to images by default. If you're using the WordPress plugin, then those classes are added since that's the behaviour of the WordPress editor, and is relied upon by at least some themes to style images correctly.
