### ISSUE TITLE
Document how to use Mammoth in a browser project with ESM

### ISSUE THREAD

**Issue by benbucksch** [mwilliamson/mammoth.js#342]
There is no documentation how to use mammoth in a browser project with ESM. The usual `import mammoth from 'mammoth';` leads to errors like "Stream not defined" and "Buffer not defined" and all kinds of pain. Eventually, it became clear that this loads the node.js version of the library. Many common libraries automatically to both node.js and browser, but not mammoth.

The PR #341 documents how to use Mammoth in a browser project with ESM.

**Comment by kchan438** [comment]
Also having an issue trying to import the module, potentially it could be an issue with vite and I'm currently on vite 3.1.3

Happens when calling `mammoth.convertToHtml(...)...`

![Screenshot 2022-10-19 205538](https://user-images.githubusercontent.com/13128842/196852747-097ecf00-d042-43a0-8d84-27db94f0e82f.png)

**Comment by mwilliamson** [comment]
In the past, bundlers tended to automatically polyfill in things like `Buffer` (so you could use `"mammoth"` rather than the standalone browser bundle), but that's increasingly no longer the case. Since the browser and node are closer than they used to be, I've had a go at updating the code to support use in the browser without polyfills. If anyone would like to try it out and report back on how it works in browser environments (and indeed node.js environments), that'd be handy for testing. The updated code is in the `browser-no-polyfills` branch, which you should be able to install with something like:

```
npm install mwilliamson/mammoth.js#browser-no-polyfills
```

**Comment by mwilliamson** [comment]
Closing since I don't think this has anything to do with ESM, but whether or not the chosen bundler automatically polyfills node.js core modules.
