### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by Xiemouren666666** [mwilliamson/mammoth.js#365]
Hello,I have a question,

`>                
                // console.log(file);
                var fileReader = new FileReader();
                var dataFile = file.raw;
                fileReader.readAsArrayBuffer(dataFile)
                fileReader.onload = function(e){
                    const array = e.target.result;
                    console.log(array);
                    // e.target.result
                    mammoth.convertToHtml({arrayBuffer:array}).then(res=>{
                        console.log(res);
                    })
                }
`
But i am still getting ReferenceError :
`
Unhandled rejection ReferenceError: Buffer is not defined    
at uint8ArrayToBuffer...
`
My development environment：
window，Chrome 113 ，vue3 ，vue-cli， webpack @4.6.3

**Comment by mwilliamson** [comment]
If you're not using the browser bundle, then you'll need to polyfill the node.js dependencies, such as `Buffer`. Using the browser bundle means you don't need to polyfill, but might be heavier (since it includes all dependencies). [The README has more details](https://github.com/mwilliamson/mammoth.js#library).
