### ISSUE TITLE
Problems with mammoth

### ISSUE THREAD

**Issue by Z3roCoder** [mwilliamson/mammoth.js#46]
There are a few huge Errors. For once, it does not keep up the document structure.
Second, it can not display textboxes.
Third, if a picture-type like emf or svg is present in the word document, there should be something like a conversion so that browsers can show it as well.

A sample file would be here: https://www.dropbox.com/s/pqux3oqq3z7lw8m/Dok1.docx?dl=0

Tested on the actual version of mammoth, Windows 7 64-Bit, actual NodeJS Version

**Comment by mwilliamson** [comment]
> For once, it does not keep up the document structure.

What do you mean by "document structure"? Could you give an example?

> Second, it can not display textboxes.

Yup, already logged here: https://github.com/mwilliamson/mammoth.js/issues/32. Given that textboxes are outside of the normal flow of text, it's not entirely obvious how they should be handled. Having said that, it shouldn't be too hard to add some basic support.

> Third, if a picture-type like emf or svg is present in the word document, there should be something like a conversion so that browsers can show it as well.

Lack of EMF support is logged here: https://github.com/mwilliamson/mammoth.js/issues/36. Unfortunately, due to the way that EMF works (i.e. being heavily tied to Windows), adding support is likely to be difficult. As for SVG: I was unaware that SVG was supported in docx files. The example you linked to only appears to contain EMF and PNG files.

The example you gave appears to be a poster rather than prose or similar. As such, I'd suggest that Mammoth probably isn't the right tool for the job: Mammoth is mainly for converting semantically marked up docx files into sensible HTML, rather than producing a high-fidelity copy in HTML. Having said that, any contributions you have for resolving the issues you've described are welcome in the form of pull requests.

I also noticed you opened another issue: https://github.com/mwilliamson/mammoth.js/issues/45. Based on the content of this issue, can I assume that you resolved your original issue?

**Comment by mwilliamson** [comment]
Closing since there are already issues logged for the missing features. Feel free to open another issue if there's other specific functionality that you think is missing.
