### ISSUE TITLE
Class repeatedly added on run style

### ISSUE THREAD

**Issue by andrewcowley** [mwilliamson/mammoth.js#58]
Hi I've been really enjoying using Mammoth (I even sent an email with words to that effect a few months ago), but I'm having an issue with the run styles. See below:
With this XML:

````
<w:r w:rsidRPr="00B803E3">
    <w:rPr>
        <w:rStyle w:val="X-reference"/>
    </w:rPr>
    <w:t xml:space="preserve">Figure </w:t>
</w:r>
<w:r w:rsidR="00BA54E2">
    <w:rPr>
        <w:rStyle w:val="X-reference"/>
    </w:rPr>
    <w:t>3.1</w:t>
</w:r>
````

This style map (I've tried :fresh too): `r[style-name='X-reference'] => span.X-reference`

I'm getting this HTML 

````
<span class="X-reference">Figure </span>
<span class="X-reference">3.1</span>
````

Ideally it would just be
````
<span class="X-reference">Figure 3.1</span>
````

I can see why I am getting the two `<span>` elements as there are two XML `<w:r>` elements. Having one `<span>` element instead of two would be ideal though. 

Is this a bug with Mammoth, or am I using it incorrectly?

**Comment by mwilliamson** [comment]
Mammoth currently creates separate elements for each run. It's possible to collapse elements together in the same way as is done for paragraphs, but it's never been implemented. So, it's Mammoth, not you.

**Comment by andrewcowley** [comment]
Thanks for getting back to me. If you see the collapsing of elements for the run styles as useful I'd be happy to have a crack at implementing it.

A point in the right direction would definitely be helpful though. If you have some spare moment a pointer to where this is done for paragraphs etc. would be very handy to get me started. Cheers!

**Comment by mwilliamson** [comment]
I think collapsing run styles makes sense. The way it works for paragraphs is that elements are kept open by the HTML generator until they need to be closed. The actual conversion to HTML takes place in `lib/document-to-html.js`. The bit that's probably most pertinent is the call to `html.satisfyPath()`, which is implemented in `lib/html-generator.js`.

Runs are converted using the same code, but they always appear in separate elements since each one gets a fresh HTML generator. This was done for ease of implementation: there's plenty of elements that get added onto the stack for runs besides the style mapping, so getting styles and the other elements working together requires a bit of thought. I have a suspicion that what would actually be easier would be to just generate the HTML as an AST without any collapsing at all (keeping track of which elements need to be fresh). Then, once the entire tree is built, non-fresh elements can be collapsed together.

Anyway, if you fancy having a go, you'd be more than welcome. I'm a bit picky on code style, so feel free to ask me questions before it's finished, and any changes or new functionality should be covered by tests. Otherwise, I'll take a look when I get a chance.

**Comment by andrewcowley** [comment]
Hi Michael,

It might be a bit tricky, but I've got some time over the next few days so I'll have a look. Thanks for the run down!

**Comment by mwilliamson** [comment]
The latest version of mammoth.js should fix this if you want to give it a whirl.
