### ISSUE TITLE
Support Table of Contents

### ISSUE THREAD

**Issue by JohnMcLear** [mwilliamson/mammoth.js#8]
Right now we don't have any linkify/table of contents support, it'd be nice to have :)

**Comment by joerou** [comment]
Hello,

For me Table of contents sometimes will show up, however, the word generated reference lists never show up as well as the word generated in text citations. Perhaps these problem are related to this issue? :)

**Comment by mwilliamson** [comment]
Hello! I'm not currently working on support for table of contents since it doesn't appear to be something that most people need. If there are other features missing, such as references or citations, then feel free to open separate issues, preferably with minimal example documents and the expected HTML output so that I know I'm actually looking at the right thing.

**Comment by joerou** [comment]
The reason I didn't open a separate issue is because I believe they are related, any word generated table such as the table of contents or the works cited or the word generated in text citations don't seem to make it. If you have an idea of what the problem might be, I would be interested in making a pull request :)

**Comment by mwilliamson** [comment]
If you provide some minimal example documents, I can take a look and see what would be involved in adding support.

**Comment by joerou** [comment]
[testdocument.docx](https://github.com/mwilliamson/mammoth.js/files/322240/testdocument.docx)
[testdocument.txt](https://github.com/mwilliamson/mammoth.js/files/322241/testdocument.txt)

So this document has a table of contents generated by word, in text citation generated by word, a cover page generated by word and also a references section generated by word and the html output is as you can basically empty.

Thanks in advance!

**Comment by mwilliamson** [comment]
Thanks for providing the document. Sorry to be a pain, but would it be much trouble to provide separate documents for each feature?

**Comment by joerou** [comment]
Nope, no problem at all! The cover page is not so important and maybe is unrelated, but the rest I think are all related to the same problem, let me know if you need something else regarding this issue.
[testdocument_cover_page.docx](https://github.com/mwilliamson/mammoth.js/files/322937/testdocument_cover_page.docx)
[testdocument_works_cited.docx](https://github.com/mwilliamson/mammoth.js/files/322938/testdocument_works_cited.docx)
[testdocument_intext_citation.docx](https://github.com/mwilliamson/mammoth.js/files/322936/testdocument_intext_citation.docx)
[testdocument_TOC.docx](https://github.com/mwilliamson/mammoth.js/files/322935/testdocument_TOC.docx)

**Comment by mwilliamson** [comment]
Thanks, I'll take a look when I get a chance. If you could provide corresponding examples of what you'd expect the HTML to look like, that would be handy too.

**Comment by rvanlaak** [comment]
Interesting! About the formatting:

> The <w:fldSimple> element will contain a run with a cached version of the field value from the last time the field was updated. 

http://officeopenxml.com/WPfields.php

So the xml will look like:

```xml
<w:fldSimple w:instr="AUTHOR">
    <w:r>
        <w:t>Marcel Proust</w:t>
    </w:r>
</w:fldSimple>
```

**Comment by mwilliamson** [comment]
From a quick look, this actually looks quite straightforward assuming no special handling. Could you try the latest version on `master` and see if that gives you the results you expect?

**Comment by joerou** [comment]
I have now tested this for the table of contents, the reference list and for in text citations, all seems to be working good! If you could just bump the version number then I can npm install the latest version and all is fixed :) Thanks again!

**Comment by mwilliamson** [comment]
Great, I've just released 1.0.4 on npm.

**Comment by ryanfitzer** [comment]
Regarding the TOC support, is there any documentation? When I'm converting a docx file with a Word-generated TOC into HTML, the headings in the content contain anchors (ex. `<h1><a id="_Toc462835598"></a>Section 1</h1>`, but the TOC items do not.

Also, the TOC items contain the page number with no way to wrap it with an element via the `styleMap`. For example, if I have an `h1` on page 1 with the text `Section One`, the TOC text for that item becomes `Section One 1`.

**Comment by mwilliamson** [comment]
Mammoth is just reading whatever the saved content is (from memory, whatever the value of `w:sdtContent` is). The anchors exist because there are bookmarks in the Word document at those locations: if there aren't anchors in the table of contents, that's because Word hasn't put in any bookmarks in the table of contents (or if it has and Mammoth isn't detecting them, there's a bug).

Similarly for the page numbers, Mammoth is just rendering whatever is present in the document. If there's a way to get different parts of the table of contents to render with a different run style (also called a character style), then you add a style map for that specific run style.

**Comment by ryanfitzer** [comment]
[This is what the `<w:p>` element looks like](https://gist.github.com/ryanfitzer/1c59a65d4b51635b3e11a76c13a3e3fc) for what I described above.

Not sure how (or if) the `<w:instrText>` element that contains the ID is parsed.

**Comment by mwilliamson** [comment]
`w:instrText` elements aren't handled at all: you should be getting a warning that the element is being ignored.

**Comment by ryanfitzer** [comment]
That warning does appear. Didn't click until I examined the xml.

Regarding the issue's title then, what support for TOC does it refer to? Reading through the thread doesn't really call that out specifically.

**Comment by mwilliamson** [comment]
For some generated elements in Word, such as tables of contents, Word
saves a copy of the generated elements in the w:sdtContent element.
Mammoth just uses that element. In other words, it's not specifically
supporting the table of contents: it's just using whatever Word has
already generated.

**Comment by rmzelle** [comment]
> w:instrText elements aren't handled at all

@mwilliamson, it's not possible to create a style map to target "instrText"? I'm trying to use mammoth.js to extract the contents of field codes with `styleMap: ["instrText => div.csl"]`, but this gives the message: 

> Did not understand this style mapping, so ignored it: instrText => div.csl Error was at character number 1: Expected element type but got identifier "instrText"

**Comment by mwilliamson** [comment]
No, afraid not.

**Comment by mwilliamson** [comment]
Is it not possible to apply run styles to specific parts of the table contents? That should be enough to do what you want.
